#!/bin/bash
set -e

: ${AKAROS_ROOT:=${HOME}/projects/akaros/}
: ${AKAROS_XCC_ROOT:=${HOME}/install/x86_64-ucb-akaros-gcc}

KFS=${AKAROS_ROOT}/kern/kfs/
XCC=${AKAROS_XCC_ROOT}/bin/x86_64-ucb-akaros-gcc
AKAROS_CFLAGS="-fno-omit-frame-pointer -g -std=gnu99"
AKAROS_LDFLAGS=""
AKAROS_LIBS="-liplib -lpthread"

function bootstrap()
{
	autoreconf --install
}

function configure()
{
	rm -rf build; mkdir build; cd build
	CC=${XCC} CFLAGS=${AKAROS_CFLAGS} LDFLAGS=${AKAROS_LDFLAGS} \
	LIBS=$AKAROS_LIBS ../configure \
	  --prefix=${KFS} \
	  --sbindir=${KFS}/bin \
	  --host=$(basename ${XCC%-gcc}) \
	  --disable-zlib \
	  --disable-openpty \
	  --disable-syslog   \
	  --disable-shadow    \
	  --enable-bundled-libtom \
	  --disable-lastlog \
	  --disable-utmp     \
	  --disable-utmpx     \
	  --disable-wtmp       \
	  --disable-wtmpx    \
	  --disable-loginfunc \
	  --disable-pututline  \
	  --disable-pututxline
	cd -
}

bootstrap
configure

cat << EndOfMessage

Dropbear has now been configured for Akaros!
Please cd into the 'build' directory and run the following 
commands to install it into the KFS of your Akaros tree.

$ cd build
$ make
$ make install

EndOfMessage
